const authorsByLetter = {
  A: [
    "David Adler",
    "Giorgio Agamben",
    "Marko Andelić",
    "Pamela Anderson",
    "Alba Arikha",
    "Avigdor Arikha",
    "Stanley Aronowitz",
    "Renata Avila",
  ],
  B: [
    "James Baldwin",
    "Ulrich Baer",
    "Roger Ballen",
    "Anthony Barnett",
    "Rosemary Bechler",
    "Julien Benda",
    "Walter Benjamin",
    "Franco Berardi",
    "John Berger",
    "Jorge Luis Borges",
    "Peter Bratsis",
    "Timothy Brennan",
    "Francesca Bria",
    "David Broder",
    "Bill Brown",
  ],
  C: [
    "Pierre Caizerguess",
    "Agnes Callard",
    "Albert Camus",
    "Cornelius Castoriadis",
    "Anton Checkhov",
    "G. K. Chesterton",
    "Noam Chomsky",
    "John Christensen",
    "Jean Clair",
    "Jean Cocteau",
    "Joseph Conrad",
    "Simon Critchley",
  ],
  D: [
    "Denis Diderot",
    "Lauro De Bosis",
    "Sebastian de Diesbach",
    "Fabio De Masi",
    "Euphrosyne Doxiadis",
    "Marguerite Duras",
  ],
  E: ["Brian Eno", "Daniel Erlacher"],
  F: ["Monica Ferrando", "Efthimis Filippou", "Ian Fleming", "E. M. Forster"],
  G: [
    "James Galbraith",
    "Mahatma Gandhi",
    "Jacques Gautrat",
    "Ksenia Gerasimova",
    "Bobby Gillespie",
    "Christian Gliwitzky",
    "Jean-Luc Godard",
    "Kenneth Goldsmith",
  ],
  H: [
    "Knut Hamsun",
    "Seán Hemingway",
    "Alice-Mary Higgins",
    "Olivier Hoedeman",
    "Baron d'Holbach",
    "Srećko Horvat",
    "Sam Hufton",
    "Aldous Huxley",
  ],
  I: [],
  J: [
    "Tim Jackson",
    "Anton Jäger",
    "Katrín Jakobsdóttir",
    "Leila Jancovich",
    "Tony Judt",
  ],
  K: ["Naomi Klein"],
  L: [
    "Kenneth Lapatin",
    "Paul Laverty",
    "D. H. Lawrence",
    "Stephen Leacock",
    "Claude Lefort",
    "Mark Lilla",
    "Jill Lloyd",
    "Ken Loach",
    "Caroline Lucas",
    "Jean-François Lyotard",
  ],
  M: [
    "Dora Malech",
    "Miltos Manetas",
    "Katherine Mansfield",
    "Riccardo Manzotti",
    "Lorenzo Marsili",
    "Raoul Martinez",
    "Alberto Masó",
    "Bill McKibben",
    "David McWilliams",
    "Walter Benn Michaels",
    "Savvas Michail",
    "John Milton",
    "Aleksandar Mirčov",
    "Vlassis Missos",
    "Paula Modersohn-Becker",
    "Jakob Mohr",
    "Evgeny Morozov",
    "Robert Musil",
  ],
  N: [
    "Preethi Nallu",
    "Lynda Nead",
    "Antonio Negri",
    "Warren Neidich",
    "Friedrich Nietzsche",
    "Rasmus Nordqvist",
  ],
  O: [],
  P: [
    "Tim Parks",
    "Xristina Penna",
    "Michael Peppiatt",
    "Fernando Pessoa",
    "Ann Pettifor",
    "Andreas Philippopoulos-Mihalopoulos",
    "Gerardo Pisarello",
  ],
  Q: [],
  R: [
    "Adam Ramsay",
    "Adolph Reed Jr.",
    "Rainer Maria Rilke",
    "David Rieff",
    "Denis Jaromil Roio",
    "Jerome Roos",
    "Bertie Russell",
  ],
  S: [
    "Maurice Saatchi",
    "Jeffrey Sachs",
    "Edward Said",
    "Saskia Sassen",
    "Thomas Schlesser",
    "Chief Seattle",
    "Seneca the Younger",
    "Andres Serrano",
    "Vladimir Šestović",
    "Elif Shafak",
    "Lee Siegel",
    "Nicholas Shaxson",
    "Georges Simenon",
    "Michael Skafidas",
    "Quinn Slobodian",
    "Pierre Souyri",
    "Nigel Spivey",
    "Jonas Staal",
    "Rainer Stamm",
    "Benno Sternberg",
    "Bram Stoker",
    "Andrew Stewart",
    "Lyndsey Stonebridge",
    "Danae Stratou",
    "Jonathan Swift",
  ],
  T: ["Gabriele Tinti", "Constantine Tsoucalas"],
  U: [],
  V: ["Raoul Vaneigem", "Yanis Varoufakis"],
  W: [
    "Pawel Wargan",
    "Eyal Weizman",
    "H. G. Wells",
    "Cornel West",
    "Edith Wharton",
    "Virginia Woolf",
  ],
  X: [],
  Y: [],
  Z: ["Daniel Zamora", "Slavoj Žižek", "Shoshana Zuboff", "Stefan Zweig"],
};

export { authorsByLetter };
